spring:
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show-sql: true
        use-sql-comments: true
        format-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 10001

eureka:
  client:
    enabled: true
    fetch-registry: false
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka